name: bsgp7030-assignment5a-ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyter
  - notebook
  - ipykernel
  - nbclient
  - nbformat
